### ISSUE TITLE
Element Already Registered Error with Workflows

### ISSUE THREAD

**Issue by ajdunker** [yannick-beot-sp/vscode-sailpoint-identitynow#101]
**Describe the bug**
After opening the list of workflows from one tenant - I try to view the list from a second. I receive the following error:

> Element with id [ID] is already registered

**To Reproduce**
1. Go to 'ISC Extension->Tenant 1->Workflows'
2. Click on 'Tenant 2->Workflows.'

**Expected behavior**
I would expect the set of workflows from the second tenant to open.

**Screenshots**
![SCR-20241206-krez](https://github.com/user-attachments/assets/f4716888-31c2-4d7a-92a9-d0284220f12d)

**Environment**
Provide a screenshot of *Help* > *About*.
![SCR-20241206-krki](https://github.com/user-attachments/assets/6da50e44-6f0a-466e-887e-81afaa5b87aa)

**Logs**
Here is a section:
```
notificationsAlerts.ts:40 Error: Element with id 22fa52d9-20a7-434f-a8f4-afda18ded9e7 is already registered
c @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
B @ event.ts:1243
C @ event.ts:1254
fire @ event.ts:1278
addNotification @ notifications.ts:228
error @ notificationService.ts:208
(anonymous) @ mainThreadTreeViews.ts:284
Promise.then
then @ lazyPromise.ts:83
getChildren @ mainThreadTreeViews.ts:278
getChildren @ treeView.ts:377
getChildren @ treeView.ts:1157
I @ asyncDataTree.ts:1334
H @ asyncDataTree.ts:1292
G @ asyncDataTree.ts:1275
F @ asyncDataTree.ts:1261
E @ asyncDataTree.ts:1230
J @ asyncDataTree.ts:1353
(anonymous) @ event.ts:1670
(anonymous) @ event.ts:1719
bufferEvents @ event.ts:1719
setCollapsed @ indexTreeModel.ts:384
setCollapsed @ objectTreeModel.ts:257
toggleCollapsed @ abstractTree.ts:2990
v @ abstractTree.ts:2461
(anonymous) @ event.ts:187
B @ event.ts:1243
fire @ event.ts:1274
(anonymous) @ event.ts:136
B @ event.ts:1243
fire @ event.ts:1274
s @ event.ts:40
```

**Additional context**

**Comment by yannick-beot-sp** [comment]
Quickly fixed in 1.3.9. 
I hope I did not break anything else...
