### ISSUE TITLE
New Functionality Ideas

### ISSUE THREAD

**Issue by justinhaines** [yannick-beot-sp/vscode-sailpoint-identitynow#13]
Would it be possible to incorporate Roles and Identity Profile functionality in the tool?

**Comment by yannick-beot-sp** [comment]
Hi @justinhaines 
Beware that the idea is not to replace IDN 😄
The thing with roles is that there might be a lot of them and the tree view would not be adapted.
What would you like to do with this extension for roles?

Regarding the identity profile: Identity profiles are part of the exportable configurable using the "SP Config" API.
At this moment, it is possible to export them through the extension and this "SP Config" API but not to import them yet.
My plan is to be able to import the configuration in a short term. 
I would need to do some research around identity profiles API as I hardly ever use this API.

**Comment by emarks-ipllc** [comment]
From an "Identity Profile" perspective, the sp_config API does not export the LifeCycle states tab/portion which is a bit of a gap.  If the LifeCycle portion could be included that would be GREAT!

**Comment by colin-mckibben-sp** [comment]
> From an "Identity Profile" perspective, the sp_config API does not export the LifeCycle states tab/portion which is a bit of a gap. If the LifeCycle portion could be included that would be GREAT!

@emarks-ipllc Can you create an idea for adding the lifecycle states information to the identity profiles portion of SP Config?  It helps me advocate for API enhancements when product can see users asking for this.  Link to ideas portal: https://developer-sailpoint.ideas.aha.io

**Comment by MicahWallace** [comment]
Is it possible to put comments in the transforms?  Looking at this list of transforms (https://community.sailpoint.com/t5/IdentityNow-Wiki/Operations-in-IdentityNow-Transforms/ta-p/72176) it appears that comments can be added with "//" in front of the line, but any time I try to do this through VSCode I get an error of (SyntaxError: Unexpected token / in JSON at position 2)

Would it be possible to add comments?  This would be very helpful for keeping documentation up to date.

**Comment by yannick-beot-sp** [comment]
Hi @MicahWallace 
Simply put, JSON does not support comments.
If you save your transform from the VSCode plugin, it will push it to IdentityNow and refresh your screen.
IdentityNow, like any other REST Server does not keep comments and the comments are removed.
The thing we can do is:
1. Save the transform on your disk
2. Add a capability to import the file. This import capability must define how to proceed with ids. Meaning, if an id is present, do we update the transform or do we skip it? This feature remains to be developed.

**Comment by yannick-beot-sp** [comment]
@justinhaines management of Identity Profiles has been added. Please give it a try!

**Comment by yannick-beot-sp** [comment]
Management of roles and access profiles has been released as part of 0.0.24.
