### ISSUE TITLE
Rules not populating from Tenant

### ISSUE THREAD

**Issue by ghost** [yannick-beot-sp/vscode-sailpoint-identitynow#21]
Working through a few different tenants, ones that I know for certain have rules uploaded to them. 
The Rules folder consistently displays, what looks to be, 4 example rules (After AD AccountCreate, After AD AccountModify, After Operation Rule Template for Web services, Before Operation Rule Template for web services), but does not show any of the other rules populated on the tenant.

**Comment by yannick-beot-sp** [comment]
Hi,
The extension is leveraging the beta API for connector rules: https://developer.sailpoint.com/apis/beta/#operation/getConnectorRuleList. Using this API allows to create, update and delete rules.
It does not include the "Cloud Rule", rules that execute only in the cloud.
Can you check with a REST client and the [API](https://developer.sailpoint.com/apis/beta/#operation/getConnectorRuleList) that nothing else is returned? Can you confirm that you are using cloud rules or rules pushed by PS?
