### ISSUE TITLE
Export config incomplete

### ISSUE THREAD

**Issue by rob-buskens-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#25]
A multi-file export worked for several of the tenants I have configured.
However for one, it only exports sources. The only thing I can think of that is different for this tenant, is I renamed it using the IDN plugin.

**Comment by yannick-beot-sp** [comment]
Not sure this capability was used and I was thinking of removing it. So, good to know this might be useful.
I have tested on my side and everything is working properly.
There is no reason that only a subset is exported knowing that:
- We rely on the sp-config endpoint to create the export
- We "explode" the results into files.


The only reasons that only sources are exported and that I can think of are pretty silly:
- Object types not selected
- Nothing to export (no identity profile, no transform, etc.)

Does a single-file export contains something else?

Can you check:
- VSCode logs
  - Go to the menu "Help" > "Toggle Developer Tool" and look if there is any error
 - Test with postman or something else the [sp-config](https://developer.sailpoint.com/apis/beta/#tag/SP-Config) export and see if anything is wrong in the exported content

**Comment by rob-buskens-sp** [comment]
I like this feature as it makes it easy to get the data out of IDN and in separate files so that I can compare two environments. 

tried single file export (everything came) and then I tried multi-file and this time everything came.

Curious.

The only difference is I usually have multiple VS Code windows open looking at different folders. I try to use the IDN plugin in only one window... but don't always keep track of it.

I'll close this. If it happens again, will follow the "Can you check" items.

Thanks,

Keep up the good work. The plugin is a primary part of my daily workflow. it makes lots of thing easier.

**Comment by yannick-beot-sp** [comment]
Thanks for your feedback and closing this issue.
Comparison between 2 environments is quite requested. 
VSCode has capabilities around this. Once you have opened the "files" with the extension, you can select them and compare them
![2022-09-28 10_41_05-Derive FirstInitial+LastName In Upper - vscode-sailpoint-identitynow - Visual St](https://user-images.githubusercontent.com/82362286/192732510-757ba137-4388-45f1-ab82-d8e9ef7c4a5d.png)

![image](https://user-images.githubusercontent.com/82362286/192732399-50f1b5eb-400a-40e8-910d-0a4ad0664ac1.png)

If you would like a specific capability, do not hesitate to reach out or create an issue for this.
