### ISSUE TITLE
feature request: source reset options supported

### ISSUE THREAD

**Issue by rob-buskens-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#26]
For the source reset option, add support for ?skip=entitlements which removes accounts, but not entitlements or roles

see: [resetting a source](https://documentation.sailpoint.com/saas/help/sources/managing_sources.html#resetting-a-source)

I've had to remove all accounts on a couple of occasions but did not want to lose the roles.

**Comment by rob-buskens-sp** [comment]
Additional menu items please. It’s a small number of options and mostly I’ve reset all.

Although skipping entitlements might become my go to.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yannick-beot-sp** [comment]
Implemented in v0.0.14

**Comment by yannick-beot-sp** [comment]
Implemented in v0.0.14
