### ISSUE TITLE
BUG: special character handling

### ISSUE THREAD

**Issue by stephen-holinaty-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#33]
it seems that the VSCode module may not be handling special characters in the appropriate UTF-8 encoding.

The IdentityNow transform documentation ( https://developer.sailpoint.com/idn/docs/transforms/operations/decompose-diacritical-marks ) gives examples of some special characters that should be parsed.

creating a transform via the VSCode module of:
`

{

    "type": "decomposeDiacriticalMarks",
    
    "attributes": {
    
        "input": "Āric Dubçek"
        
    },
    
    "name": "ProofOfConcept"
    
}

`

Should, per the documentation, yield "Aric Dubcek" as the result.

However, retrieving this same transform via the REST APIs of Identitynow, yields a very different transform:
`{

    "id": "redacted",
    
    "name": "ProofOfConcept",
    
    "type": "decomposeDiacriticalMarks",
    
    "attributes": {
    
        "input": "Äric DubÃ§ek"
        
    },
    
    "internal": false
    
}`

and utilizing the transform in an Identity Profile yields the resultant value of:
`Aric DubA§ek`

If i use the same initial transform directly in Postman via the APIs, or run an Update to re-set the Input value to the correct value, the output is as expected... Aric Dubcek

**Comment by yannick-beot-sp** [comment]
Fixed in v0.0.15
