### ISSUE TITLE
Error when exporting rule to file

### ISSUE THREAD

**Issue by jlazerus1** [yannick-beot-sp/vscode-sailpoint-identitynow#35]
I'm receiving this error while trying to export a rule to file. I'm on version v0.0.15. Tried v0.0.14 as well but getting the same issue.

Error running command vscode-sailpoint-identitynow.connector-rule.export-script.view: e.replace is not a function. This is likely caused by the extension that contributes vscode-sailpoint-identitynow.connector-rule.export-script.view.

**Comment by yannick-beot-sp** [comment]
Which OS are you using?
Did you open a folder with VSCode before exporting?

**Comment by yannick-beot-sp** [comment]
I was able to reproduce it. It will be fixed in v0.0.16. I'll close it as soon as the v0.0.16 is released
