### ISSUE TITLE
Cannot read properties of null (reading 'toLowerCase')

### ISSUE THREAD

**Issue by Ramana075** [yannick-beot-sp/vscode-sailpoint-identitynow#38]
We are getting the below exception while opening the sources.
Cannot read properties of null (reading 'toLowerCase')

**Comment by yannick-beot-sp** [comment]
Which version are you using? 0.0.15?
Can you give me a screenshot of **Help** > **About**?
Do you have any sources? Was it working?
Can you try to delete the tenant and recreate it?

Note: I have changed the way to sort sources for 0.0.16. Unfortunately, there is an issue for publishing it. You can manually download and install the VSIX from https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/releases/tag/releases%2Fv0.0.16.

**Comment by yannick-beot-sp** [comment]
How many sources do you have for this tenant?

**Comment by Ramana075** [comment]
More than 50 sources

**Comment by yannick-beot-sp** [comment]
Can you try the version 0.0.16?
Dowload the VSIX file from https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/releases/tag/releases%2Fv0.0.16.
The VSIX can be installed from the extension menu. Press `Ctrl+Shift+X` to open the extension menu and in the menu, click `Install from VSIX...`.

**Comment by Ramana075** [comment]
Yes, I try using 0.0.16 version, getting the below error
The "path" argument must be of type string. Received type object

**Comment by yannick-beot-sp** [comment]
I guess you get this error by trying to open "sources" as well.
I tried to reproduce by using special characters in source name but I is working without error.
I'm using exactly the same environment (version and all) on a tenant with 56 sources successfully.
I'm trying to find a clever way of sharing the output to the call to `{{api-url}}/v3/sources?limit=250&count=true&offset=0` so I can analyze it.

Can you make this call with Postman for instance and extract the source name by using the JSONPath `$[*].name` (with https://jsonpath.com/ or something else). You should get something like

```
[
  "Workday",
  "SAP ERP",
  "Office 365 rooms",
  "Workplace",
...
```

**Comment by yannick-beot-sp** [comment]
Hi @Ramana075 
Here is a link to share the output of the call described above: https://colibris.link/d7pt7
It is a tool used by SailPoint's support. If it helps...

**Comment by Ramana075** [comment]
I am able to open the all source in VS code now, Thanks you

**Comment by yannick-beot-sp** [comment]
@Ramana075 Do you have any idea how you got a "null" source?

**Comment by Ramana075** [comment]
Yes, with some wrong sp-config import the null source got created.

**Comment by yannick-beot-sp** [comment]
Interesting. Thanks.
