### ISSUE TITLE
Enhanced credential management for multiple-tenant usage

### ISSUE THREAD

**Issue by stephen-holinaty-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#40]
When connecting the VSCode module to multiple tenants, if you make an error with a credential or have issues, you have to remove/re-add the tenant to VSCode

**Describe the solution you'd like**
-If a credential returns invalid, immediately prompt the user for new credentials.
- add context-menu item on an existing Tenant "Update credentials" >> provide the same prompt as net-new (PAT / session token?)

**Describe alternatives you've considered**
Remove and re-add the tenant.
get mad, find out ive used the maximum number of PATs for a tenant, struggle to decide which is which.

**Additional context**
when using 1 or more tenants tied to the same VSCode, credential management becomes frustrating.
if i paste a sandbox-tenant session token into a production-tenant prompt, I can not immediately re-enter the credentials without causing additional chaos

**Comment by yannick-beot-sp** [comment]
IdentityNow now provides the "last used dates" for PAT, to help decide which is used or not.
The VSCode extension does not store anything. Adding, then removing, then adding a tenant do not make lose any information.
I already have strict validation rule for the format so you cannot pass anything else than a Client Id/Client Secret.

Session token is already annoying to use, given the short lifetime. It was only meant for support and with the help of a Chrome extension to get the session token and push it to VSCode.
