### ISSUE TITLE
Export (Mac) not handling relative paths with a ~

### ISSUE THREAD

**Issue by stephen-holinaty-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#41]
**Describe the bug**
while exporting (r-click, export sp-config), the default path/filename doesnt work, and ~/Desktop/file.xml fails. 

**To Reproduce**
Using VSCode for mac: 

right click on a source
Select "Export SP-Config"
in the "Enter the file name" box, its prepopulated with some data.  hit enter
"Error running command..." error
try again, enter ~/Desktop/file.json
"Error running command"
try again, with /usr/admin/Desktop/file.json
Success

**Expected behavior**
the "Default" filename should provide a valid export, saved... somewhere.
relative paths on mac using the ~ operator should be successful, i.e. ~/Desktop/filename.json

**Screenshots**
<img width="326" alt="Screenshot 2023-03-03 at 8 30 21 AM" src="https://user-images.githubusercontent.com/116119717/222746452-8d72f32b-2a5d-49d3-8dc4-836d0371e908.png">

**Environment**
Provide a screenshot of *Help* > *About*.

**Logs**
[Extension Host] Writing to  identitynowconfig-TENANT-sb.identitynow.com-NetSuite INTQA-2023-03-03T14-27-23.json

Error running command vscode-sailpoint-identitynow.export-node-config.view: A system error occurred (EROFS: read-only file system, open 'identitynowconfig-TENANT-sb.identitynow.com-NetSuite-2023-03-03T14-27-23.json'). This is likely caused by the extension that contributes vscode-sailpoint-identitynow.export-node-config.view.

**Comment by stephen-holinaty-sp** [comment]
@yannick-beot-sp  that is entirely fair.
is there any other way that the Default "export" can be a valid path, then?
in my mind, "Export... Enter!" should not give a failing use-case.

I'm not sure what type of default save-to location i would even propose, but as we are populating a filename into the default value, my assumption would be fore it to work.
or even to replace the default filename with 
(unix) \path\to\directory\filename.xml)
(windows) c:\filepath\filename.xml

or, put another way:
if we cant provide a valid path, at least provide a contextual breadcrumb so the user isnt stumbling to find out Why their export is failing.

**Comment by stephen-holinaty-sp** [comment]
^ good point re: workspace.
When i first open VSCode, there is no open workspace.
then i begin interacting with the IdentityNow module, try to export, and 
<img width="536" alt="Screenshot 2023-03-08 at 8 52 03 AM" src="https://user-images.githubusercontent.com/116119717/223745711-da1fcbca-8d7c-4f93-bcd6-131c0efb5728.png">
<img width="480" alt="Screenshot 2023-03-08 at 8 52 27 AM" src="https://user-images.githubusercontent.com/116119717/223745851-e30ecc69-1d8b-4958-9f74-66070bc265f9.png">

**you are correct. with a workspace open, it auto-populates:**
<img width="633" alt="Screenshot 2023-03-08 at 8 53 18 AM" src="https://user-images.githubusercontent.com/116119717/223746135-9731c3fa-8e7c-408e-8432-c6ae5a6bb0b1.png">

**Comment by yannick-beot-sp** [comment]
I started to work on being able to set the default path proposition in the settings
cf. https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/blob/63aaef66625924217aadd0d17c2eb0f572d5e62b/package.json#L622

The idea is to extend what I just did for new reports to SP-Config exports.

With this capability, you could hard code a path to export to (within your home dir or not), set the architecture of files and folders you want, have dates or not in the filename, etc.

**Comment by yannick-beot-sp** [comment]
Releases as part of https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/releases/tag/releases%2Fv0.0.19
