### ISSUE TITLE
SSL error while fetching any object from tenant 

### ISSUE THREAD

**Issue by guptah-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#45]
**Describe the bug**
After adding a production tenant, receiving an error "unable to get local issuer certificate" while fetching any object e.g. transforms. However, issue is not reproducible while working with Sandbox tenant. We are able to add sandbox tenant and fetch objects e.g. transforms.

**To Reproduce**
Add a Production Sailpoint IDN tenant using PAT
1. Go to 'Transforms'
2. Click on 'Refresh' icon
3. See error

**Expected behavior**
List of transforms names
[IDNVScodeError.pdf](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/files/11024344/IDNVScodeError.pdf)

**Screenshots**

**Environment**
Provide a screenshot of *Help* > *About*.
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19042

**Logs**
To get logs:
1. Go to *Help* > *Toggle Developer Tools*.
2. Clear the console.
3. Reproduce the error.
4. Copy/paste the logs.

**Additional context**

**Comment by yannick-beot-sp** [comment]
@guptah-sp Is this error still occuring?
