### ISSUE TITLE
Unable to refresh Identity Profile

### ISSUE THREAD

**Issue by gwhip70** [yannick-beot-sp/vscode-sailpoint-identitynow#53]
This error occurred when refreshing an identity profile in our Sandox tenant

Error running command vscode-sailpoint-identitynow.identity-profile.refresh: Request failed with status code 405. This is likely caused by the extension that contributes vscode-sailpoint-identitynow.identity-profile.refresh.

![image](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/assets/30579151/7a64b750-2099-4d78-a49d-b1e46e4490e8)

**Comment by yannick-beot-sp** [comment]
Just released 0.0.23 that should fix it

**Comment by yannick-beot-sp** [comment]
Just released 0.0.23 that should fix it
