### ISSUE TITLE
Detailed message needed when receiving 400 response code

### ISSUE THREAD

**Issue by gwhip70** [yannick-beot-sp/vscode-sailpoint-identitynow#54]
When performing Source Reset all that was displayed was a response code of 400.

Upon running the same command in Postman the same message was displayed but with a couple of additional details over time that provided a better explanation.

1. Detailed message was that it can't be proceed because there was an Identity Refresh process running and the source could not be reset at that time.
2. After the Identity Refresh was complete this was the message displayed in Postman:
    "msg_template": "Source 'xxx' is currently in use.",
    "slpt_error_code": "SLPT-1209",
    "formatted_msg": "(SLPT-1209) Source 'xxx' is currently in use.",
    "exception_id": "18B206C5CA9",
    "error_code": 1209,
    "exception_class": "com.cloudmasons.exceptions.SLPTSourceInUseException",
    "exception_detail": {
        "file": "SourceService.groovy",
        "method": "reset",
        "line_number": 2140,
        "sourcesOwnedByUsersFromThisSource": [
            "xxyy",
            "yyxx",
            "yyyy"
        ],
        "class": "com.cloudmasons.SourceService"
    },
    "http_response_code": 400,

It would be nice if the message details in the IDN extension contained at least some of this detail.

**Comment by yannick-beot-sp** [comment]
Here is what I can do for instance: 
![image](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/assets/82362286/0de35fec-c05c-4eea-89a2-127b31a78681)

**Comment by yannick-beot-sp** [comment]
Released as part of 0.0.24
