### ISSUE TITLE
Error messages during export All commands

### ISSUE THREAD

**Issue by chadcarlton** [yannick-beot-sp/vscode-sailpoint-identitynow#62]
**Describe the bug**
When trying to "export all Access Profiles as CSV" via the right click menu item after inputting a filename, receive error message: 

`Error running command vscode-sailpoint-identitynow.csv.export.access-profiles.view: Request failed with status code 429. This is likely caused by the extension that contributes vscode-sailpoint-identitynow.csv.export.access-profiles.view.`

An error is also seen when trying to use "export all roles as CSV" via the right click menu item after inputting a filename: 

`Error running command vscode-sailpoint-identitynow.csv.export.roles.view: Cannot read properties of null (reading 'property'). This is likely caused by the extension that contributes vscode-sailpoint-identitynow.csv.export.roles.view.`

It is unclear how to resolve these.

**To Reproduce**
1. Right click on "Access Profiles" or "Roles" and choose export
2. put a path and filename in place (or accept defaults)
3. Encounter error

**Expected behavior**
exports should occur, and without error.

**Comment by yannick-beot-sp** [comment]
Can you try the new release v0.0.26?

**Comment by yannick-beot-sp** [comment]
@chadcarlton does the latest release (v0.0.27) solve this issue?

**Comment by yannick-beot-sp** [comment]
@chadcarlton without any answer, I'll close this issue.
Let me know if you still have an issue and we will reopen it.
