### ISSUE TITLE
Search attribute config

### ISSUE THREAD

**Issue by leigh-mason-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#64]
**Is your feature request related to a problem? Please describe.**
Account attribute rules sometimes require logic to generate a unique value (think sAMAccountName in AD). This requires the creation and maintenance of a search attribute config which isn't possible in the extension.

https://developer.sailpoint.com/idn/api/beta/search-attribute-configuration

**Describe the solution you'd like**
The ability to list current, create new, and update existing records in much the same way as transforms, sources etc. 

**Describe alternatives you've considered**
Currently, the approach to maintaining these records must be done via Postman or a similar tool against the APIs. No capability exists in the admin UI to do this.

**Additional context**

https://community.sailpoint.com/t5/IdentityNow-Wiki/How-to-Search-Non-Indexed-Account-Attributes-in-IDN-Rules-for/ta-p/205863

**Comment by iobeidi** [comment]
That would be helpfull.

**Comment by yannick-beot-sp** [comment]
Part of v0.0.30
