### ISSUE TITLE
Cannot Save Transforms 

### ISSUE THREAD

**Issue by Dylan-Blanchard** [yannick-beot-sp/vscode-sailpoint-identitynow#68]
**Describe the bug**
I can't save my transforms, every time the page refreshes the data reverts back to what it was before. 
I reimported my entire tenant: KO 
I modify teh data with Postman and https://developer.sailpoint.com/docs/api/v3/update-transform : OK 
After reading the logs (see attachment below) it seems that the PUT API call is not executed and that when the file is saved, the plugin redoes a GET, which would explain the disappearance of the data. 

**To Reproduce**
1 modify a transform
2 Save 
3 refresh the page 
4 see the changes 

**Environment**
![image](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/assets/162340202/1e48c023-3403-49a1-b191-f8d42980c4c2)

**Logs**
![image](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/assets/162340202/81c85efc-3ddd-4120-beeb-c06b2b8d4afa)

Thanks a lot ! For yor job for this plugin and for this investigation !

**Comment by iobeidi** [comment]
I'm having also this issue with Sources.

**Comment by yannick-beot-sp** [comment]
Thanks for opening this @Dylan-Blanchard 
I'll fix that and release immediately

**Comment by yannick-beot-sp** [comment]
@iobeidi for the problem for source is in the backend and different.
It think you are refering to https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/issues/67
For sources, the source is actually updated but an error is raised.

**Comment by yannick-beot-sp** [comment]
Fixed in v1.0.1

**Comment by Dylan-Blanchard** [comment]
It works perfectly, thank you for your responsiveness !
