### ISSUE TITLE
Evaluate Transform behaves differently than ISC for NormalizeName transform

### ISSUE THREAD

**Issue by stephen-holinaty-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#73]
**Describe the bug**
the VSCode "Evaluate Transform" function does not account for the specialization "mc- and mac-" naming functions

**To Reproduce**
create a transform
```{
    "name": "NormalizeNameTest",
    "type": "normalizeNames",
    "attributes": {
        "input": "mac-donalds"
    }
}
```
right click, Evaluate it in VS Code plugin
apply it to an identity attribute in ISC and process it
compare the results
VSCode gives 'MacDonalds', Tenant gives `Mac-donalds`

**Expected behavior**
VSCode "Evaluate transform" should give same results as if the tenant processed it

**Environment**
Version: 1.88.0 (Universal)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:18.899Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Additional context**
https://developer.sailpoint.com/docs/extensibility/transforms/operations/name-normalizer/

Special replacements of patterns that include "MC" and "MAC" (or case-based variations of those two strings)
The transform automatically converts "MC" to "Mc" and "MAC" to "Mac" when they are part of a patronymic last name.

**Comment by yannick-beot-sp** [comment]
@stephen-holinaty-sp 
I really wonder how that was implemented.
The rule says:
> Any string containing either a space, a hyphen or an apostrophe - the transform splits these by that character and capitalizes the first character of each resulting substring.

I would need to verify is the hyphen is used as a separator or not.

**Comment by yannick-beot-sp** [comment]
As part of v1.3.0
