### ISSUE TITLE
Ability to turn off Automatic Updating of the tenant in favor of a menu option to upload to tenant. 

### ISSUE THREAD

**Issue by GeoffAtIDW** [yannick-beot-sp/vscode-sailpoint-identitynow#76]
**Is your feature request related to a problem? Please describe.**
Yes. The issue with automatic updates is that there is no way to save incremental changes, work-in-progress, or to protect against accidental changes that may result from the save being used for the tenant. 

There is also no way to protect against the "Oops, I opened and edited the file for the wrong tenant" situation that could occur when you have more than one tenant configured in the extension. 

**Describe the solution you'd like**
There should be a configuration option to turn off automatic updated, and require a manual step to push the change to the tenant. This could be a menu item that the user selects to import the change to the tenant, similar to what the IIQDA has, or it could be a pop-up prompt when saving that asks if you would like to also push the change to the tenant.  

**Describe alternatives you've considered**
The only workable solution is to NOT use the extension when working with the code. 

**Additional context**
Junior developers are more prone to the errors that the extension currently allows, and because these errors take time to remedy, I can not recommend the use of the extension to others.

**Comment by yannick-beot-sp** [comment]
Unfortunately, JSON does not provide a convenient way to define on what kind of object somebody is working.
JSON schema are not embedded in the object returned by the API.
In XML, the root element defines automatically which object we are modifying (that being an Application, a Bundle, or else).
Also, the API offers several endpoints for each object for which we would still need to route the request to.

We could have a similar behavior as for connector rules, workflows, and forms. These objects already have commands to upload JSON or code.
Even roles and access profiles, as we can export and import them through CSV files.

We could do the same but I do not see how this could prevent any mistake. If you upload something "wrong", you can still break things.

Also, I would say that making errors is a great way to learn ;)

**Comment by GeoffAtIDW** [comment]
I would agree that you could just as easily import the wrong file, although it would be more, deliberate steps since you would need to do it from the context menu of the file itself. 

I would say it is much easier to be in the wrong document or window and press CTRL-S thinking you are saving say a Word document, and in actuality VS Code is the active window and you just saved something that you were working through, but was not complete.

In the last 2 weeks I've had 2 people from 2 separate companies state they won't use the plugin due to how easy it is to accidentally push code out, so I am trying to think of ways to improve it for more universal adoption.

**Comment by GeoffAtIDW** [comment]
Reviewing the coming change for #75, that appears to be a good interim solution given the current complexity of achieving this as described above.

**Comment by yannick-beot-sp** [comment]
Closing this as not doable today.
#75 implemented as a workaround.
Will reopen if a better technical solution shows up
