### ISSUE TITLE
reset source seems to no longer work

### ISSUE THREAD

**Issue by dryfoj** [yannick-beot-sp/vscode-sailpoint-identitynow#85]
**Describe the bug**
Not sure if this is just me (another on my team having same issue), but reset source stopped working across the board in our sandbox (not sure about prod):
Error running command vscode-sailpoint-identitynow.reset-source: Request failed with status code 400. This is likely caused by the extension that contributes vscode-sailpoint-identitynow.reset-source.

Note: Reset of entitlements does work
Reset of accounts does not work:
Error running command vscode-sailpoint-identitynow.reset-source-accounts: Request failed with status code 400. This is likely caused by the extension that contributes vscode-sailpoint-identitynow.reset-source-accounts.

**To Reproduce**
Try reset source or reset accounts

**Environment**
Version: 1.90.0 (Universal)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:44.157Z (1 wk ago)
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 23.5.0

**Logs**
1. Go to *Help* > *Toggle Developer Tools*.
This option is greyed out for me and I cannot do for some reason

**Additional context**
I have not been able to test this in our production instance, just sandbox.

**Comment by dryfoj** [comment]
Test the API call via postman and issue appears to be the API level so perhaps not a bug here:
{{baseUrl}}/beta/sources/:id/remove-accounts
{
    "detailCode": "400.1 Bad request content",
    "trackingId": "xxxxxx",
    "messages": [
        {
            "locale": "en-US",
            "localeOrigin": "DEFAULT",
            "text": "Action \"Remove Source Accounts\" cannot be performed on [xxxxxx, xxxxxx]"
        },
        {
            "locale": "und",
            "localeOrigin": "REQUEST",
            "text": "Action \"Remove Source Accounts\" cannot be performed on [xxxxxx, xxxxxxxxxx]"
        }
    ],
    "causes": []
}

**Comment by yannick-beot-sp** [comment]
Yes, There is a high chance that one the account is also owner of some
object.
I'll try to have a better error message, to have at least the "text"
property.
Unfortunately, this is not documented and not always easy to reproduce...

Le ven. 14 juin 2024 à 17:30, James Dryfoos ***@***.***> a
écrit :

**Comment by yannick-beot-sp** [comment]
Version 1.3.5 will catch more info from the error.
