### ISSUE TITLE
Sample Before Provisioning Rule for SDIM Missing

### ISSUE THREAD

**Issue by justinhaines** [yannick-beot-sp/vscode-sailpoint-identitynow#88]
**Describe the bug**
When environments are exported, the "Sample Before Provisioning Rule for SDIM" rule is not included

**To Reproduce**
1. Export Tenant
2. Review the Rules folder

**Expected behavior**
Most out-of-the-box cloud rules are excluded, but we need to include this rule because it sometimes needs to be modified.

**Comment by yannick-beot-sp** [comment]
Hi @justinhaines,
Have you tried by API directly? I'm not doing any specific filtering for rules.
So I expect that is more an "issue" with the SP Config endpoint that with the VSCode plugin.

Also, one test worth testing is Configuration Hub. Have you try to backup this rule and restore it?
You don't have to restore it really. Just created a draft will highlight what should be restored and the rule should be there.

**Comment by yannick-beot-sp** [comment]
Closing as not a problem with the extension but with SP-Config API.
