### ISSUE TITLE
Tennants loose PAT configuration if we close  VSCODE

### ISSUE THREAD

**Issue by iobeidi** [yannick-beot-sp/vscode-sailpoint-identitynow#93]
**Describe the bug**
I had to reconfigure my tennants 3 to 4 times already due to they stop connecting. the PAT are correct , but everytime i  close VSCODE the tennan t starts failling connection giving me a 401

**To Reproduce**
1. Configure a tennant
2. Insert working PAT
3. Close vscode
4. re-open vscode
5. Tennant start to give 401 problems.

**Expected behavior**
working fine

**Screenshots**
![image](https://github.com/user-attachments/assets/d2e657d1-78a4-446e-abe0-17ad9a662648)

**Logs**
Extension Host] > ISCDataProvider.forceRefresh
console.ts:137 [Extension Host] > ISCDataProvider.refresh
console.ts:137 [Extension Host] > getTreeItem 
{collapsibleState: 1, label: 'Sources', tenantId: '1e71e9ee2b8b46a2985384344d1ea330', tenantName: 'client-sb.identitynow.com', tenantDisplayName: '#55 - CPFS', …}
console.ts:137 [Extension Host] after update 
{collapsibleState: 1, label: 'Sources', tenantId: '1e71e9ee2b8b46a2985384344d1ea330', tenantName: 'client-sb.identitynow.com', tenantDisplayName: '#55 - CPFS', …}
console.ts:137 [Extension Host] > getChildren 
{collapsibleState: 1, label: 'Sources', tenantId: '1e71e9ee2b8b46a2985384344d1ea330', tenantName: 'client-sb.identitynow.com', tenantDisplayName: '#55 - CPFS', …}
console.ts:137 [Extension Host] > getSources
console.ts:137 [Extension Host] > getSessions 
['1e71e9ee2b8b46a2985384344d1ea330']
console.ts:137 [Extension Host] > getSessionByTenant 1e71e9ee2b8b46a2985384344d1ea330
console.ts:137 [Extension Host] < getSessionByTenant existing token
console.ts:137 [Extension Host] < getSessions
console.ts:137 [Extension Host] Paginating call, offset = 0
log.ts:439   ERR [Extension Host] Unable to fetch access token.  Aborting.
console.ts:137 [Extension Host] Unable to fetch access token.  Aborting.
notificationsAlerts.ts:40 Error: AxiosError: Request failed with status code 401
	at a.<anonymous> (c:\Users\Fawkes\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.2\out\extension.js:43:5496)
	at c (c:\Users\Fawkes\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.2\out\extension.js:43:2792)
	at Object.throw (c:\Users\Fawkes\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.2\out\extension.js:43:2075)
	at c (c:\Users\Fawkes\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.2\out\extension.js:43:1684)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
﻿

**Comment by yannick-beot-sp** [comment]
I have just released 1.3.3 that should fix this.
Let me know if that's not the case.

**Comment by Semperverus** [comment]
This seems to be causing a new error, re: #94
