### ISSUE TITLE
VC is prompting me to login for every object I'm trying to open

### ISSUE THREAD

**Issue by jakublempart** [yannick-beot-sp/vscode-sailpoint-identitynow#94]
**Describe the bug**
Hey,

after update -> VC is prompting me to login for every object I'm trying to open. PAT is correct (tried to create new one) in VC in profiles user is logged also I tried to reinstall extension. Is it know error or this is my env wrong config?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Provide a screenshot of *Help* > *About*.

**Logs**
To get logs:
1. Go to *Help* > *Toggle Developer Tools*.
2. Clear the console.
3. Reproduce the error.
4. Copy/paste the logs.

**Additional context**

**Comment by Semperverus** [comment]
+1 for this, also experiencing the exact same issue.

**Comment by yannick-beot-sp** [comment]
Should be fixed in 1.3.4
