### ISSUE TITLE
How to add multiple entitlements using bulk Role import

### ISSUE THREAD

**Issue by Imi-Sultan** [yannick-beot-sp/vscode-sailpoint-identitynow#96]
**Describe the bug**
Hi there. Not yet sure if this is a bug as I might be doing this wrong. How do we add multiple entitlements in the same Role using the 'Import Roles CSV' option in VS Code?

**What I've already tried**
In the entitlements cell in the CSV file, each of the below have been tried on their own:
•SourceName|entitlement1;SourceName|entitlement2
•"SourceName"|"entitlement1";"SourceName"|"entitlement2"
•SourceName|entitlement1;entitlement2
•[SourceName|entitlement1;SourceName|entitlement2]
•SourceName|entitlement1,SourceName|entitlement2
•SourceName|entitlement1|SourceName|entitlement2

**To Reproduce**
1. Click on 'Import Roles CSV' next to 'Roles' 
2. Select the relevant csv file 
3. See error '0 line(s) processed. 0 successfully import. 0 error(s)

**Expected behavior**
Message saying 'Successfully imported role [Role name]'. As well as the Role being created in the tenant with multiple entitlements added as access

**Screenshots**

**Environment**
![20241031_214149](https://github.com/user-attachments/assets/936689b4-7ca9-4107-bda3-e5df38f4b367)

**Logs**
[Extension Host] > RoleImporterTreeViewCommand.execute
console.ts:137 [Extension Host] > RoleImporter.importFile
log.ts:439   ERR ENOENT: no such file or directory, open 'C:\dev\null': Error: ENOENT: no such file or directory, open 'C:\dev\null'
notificationsAlerts.ts:42 0 line(s) processed. 0 sucessfully import. 0 error(s).
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
B @ event.ts:1242
C @ event.ts:1253
fire @ event.ts:1277
addNotification @ notifications.ts:228
notify @ notificationService.ts:253
(anonymous) @ mainThreadMessageService.ts:86
f @ mainThreadMessageService.ts:51
$showMessage @ mainThreadMessageService.ts:45
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1242
fire @ event.ts:1273
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] Governance Group Cache stats {hits: 0, misses: 0}
console.ts:137 [Extension Host] Identity Cache stats {hits: 0, misses: 0}
console.ts:137 [Extension Host] Access Profile Cache stats {hits: 0, misses: 0}
console.ts:137 [Extension Host] Source Cache stats {hits: 0, misses: 0}
console.ts:137 [Extension Host] Entitlement Cache stats {hits: 0, misses: 0}

![IMG-20241031-WA0027](https://github.com/user-attachments/assets/b8f89a73-e74e-4c2a-a9c8-0cc5fe9a9fb2)

**Additional context**
I can successfully import a Role with just one Entitlement.

**Comment by yannick-beot-sp** [comment]
I found this error `no such file or directory, open 'C:\dev\null'` super weird.
Here is the content of a working example (for my environment):
```
"name","description","enabled","requestable","owner","commentsRequired","denialCommentsRequired","approvalSchemes","revokeCommentsRequired","revokeDenialCommentsRequired","revokeApprovalSchemes","accessProfiles","entitlements","membershipCriteria"
"Vendeur agence2","",true,false,"se.admin",false,false,"",false,false,"","","Active Directory|Qlik-Vente-Lecture;Active Directory|Qlik-Vente-Agence","identity.cloudLifecycleState eq 'active' and identity.jobTitle eq 'Vendeur agence'"
```
Can you make sure to:
- Use double quotes (`"`) to _isolate_ the list of entitlements in the column `entitlements`
- Use the sem-colon (`;`) as a separator between entitlements

In any case, if I have several roles to create, I create one in the UI, export the role in CSV and then, add the necessary lines by making modification to the CSV so I don't have to remember the syntax.

**Comment by yannick-beot-sp** [comment]
@Imi-Sultan I did not get any answer to my comment. Can we close this ticket?

**Comment by Imi-Sultan** [comment]
Hi @yannick-beot-sp. Tried it again now following the steps you provided and it worked perfectly. Thank you so much for the help.

**Comment by anshuldixit8171-lgtm** [comment]
Hi @yannick-beot-sp I have tried this membership criteria but on it my job code filter is not working because of some syntax error could you please help me on it I am doing bulk role import with multiple entitlements 
here you find the membership criter where job code is C067 
@Imi-Sultan @Semperverus @RICHASG @henrique-quintino-sp 

"identity.cloudLifecycleState eq 'active' or identity.cloudLifecycleState eq 'prehire1' or identity.cloudLifecycleState eq 'prehire2' or identity.cloudLifecycleState eq 'pendingTermination' "and " identity.allJobCodes co 'AP152'"

**Comment by yannick-beot-sp** [comment]
I'd recommend to use the operator "in" in your case.
Also, I don't understand why you have `"` around `and`.

Here is something that might help:

```
identity.cloudLifecycleState in ('active','prehire1','prehire2','pendingTermination') and identity.allJobCodes co 'AP152'"
```

**Comment by anshuldixit8171-lgtm** [comment]
above query won't work 
identity.cloudLifecycleState in ('active','prehire1','prehire2','pendingTermination') and identity.allJobCodes co 'AP152'"

I need jobcode equals and need all active prehire1 prehire 2pendingTermination in one line

**Comment by yannick-beot-sp** [comment]
I don't understand what means
> I need jobcode equals and need all active prehire1 prehire 2pendingTermination in one line

I took the operator "contains" for allJobCodes because this is what you wrote above.
In any case, I would recommend to configure one role with your requirements and then export. You will have the proper expression.
