### ISSUE TITLE
Customize API path

### ISSUE THREAD

**Issue by aunefyren** [yannick-beot-sp/vscode-sailpoint-identitynow#97]
**Is your feature request related to a problem? Please describe.**
We have customers which utilize vanity URLs. This means the ISC platform is not hosted on `identitynow.com`. It can be any thing, like `sailpoint.cooldomain.com`. When adding a tenant, we are only asked for the front-end URL, not the API. On your exntension, the API URL is built from the other URL, which in this case is wrong, as the API is still hosted on the SailPoint domain. This makes me unable to add the tenants.

**Describe the solution you'd like**
Much like the Sail CLI, ask for an API URL, or give the option to provide one.

**Describe alternatives you've considered**
If I could manually alter the config files, I could perhaps just add the tenant manually through a file? I couldn't find any config files for the tenants.

**Additional context**
I couldn't find anything on here, or through Google, describing this issue.

**Comment by yannick-beot-sp** [comment]
Hi,
I never had my hand on a tenant with vanity URL.
My understanding is that for tenant with vanity URL, API URL is still in the form `.api.identitynow.com`.
I'm using the tenant URL just to calculate the API URL.
So if my assumption is correct, you could use the tenant in the form of `musupercooldomain.identitynow.com`.

**Comment by aunefyren** [comment]
I thought I tried just the API prefix, but it must have slipped my mind. Tried it now and it works. Thank you so much for the help!
