### ISSUE TITLE
Transforms do not support n>250

### ISSUE THREAD

**Issue by stephen-holinaty-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#98]
**Describe the bug**
the Transforms UI item is limited to 250 transforms, effectively blocking edits to all transforms after the first 250

**To Reproduce**
1. have 251 transforms
2. try to find #251 in the plugin

**Expected behavior**
Transforms should either have:
a) a load-more button
b) paginate automatically and return All transforms

**Environment**
![Screenshot 2024-11-27 at 12 57 57 PM](https://github.com/user-attachments/assets/bd8428be-7317-4617-b2bc-e834b12fad38)

**Comment by yannick-beot-sp** [comment]
"List transforms" does not support sorters.
I will use the "paginate" function to get all transforms, and sort by name "client side".
If there is more than 250 transforms, it's going to be a very long list -> thanks to VSCode capability, it's possible to search in the tree view

**Comment by yannick-beot-sp** [comment]
Fixed in 1.3.9.
